"""Public Fish player-state API.

The implementation is split by responsibility while this module preserves the
original import path used by engines, commands, and external callers.
"""

from .fish_state_codec import (
    FishArchiveCodec,
    FishArchiveEnvelope,
    FishCheckpointCodec,
)
from .fish_state_model import (
    DEFAULT_MAX_FUTURE_SECONDS,
    FISH_ARCHIVE_VERSION,
    FISH_ENGINE_ID,
    FISH_MAX_LEVEL,
    MAX_BIG_NUMBER_EXPONENT,
    ArchiveMeta,
    AutomationState,
    BarbellState,
    BigNumberDTO,
    BreakthroughState,
    CollectionState,
    FishHallState,
    FishInstance,
    FishInventory,
    FishStateValidationContext,
    FishStateValidationError,
    OwnedBarbell,
    PlayerState,
    ProductionState,
    RebirthState,
    StatisticsState,
    TorpedoState,
    TrashManState,
    TrashManUpgrade,
    TrashProcessingState,
    TrashStock,
    WalletState,
)
from .fish_state_serialization import normalize_player_state

__all__ = [
    "DEFAULT_MAX_FUTURE_SECONDS",
    "FISH_ARCHIVE_VERSION",
    "FISH_ENGINE_ID",
    "FISH_MAX_LEVEL",
    "MAX_BIG_NUMBER_EXPONENT",
    "ArchiveMeta",
    "AutomationState",
    "BarbellState",
    "BigNumberDTO",
    "BreakthroughState",
    "CollectionState",
    "FishArchiveCodec",
    "FishArchiveEnvelope",
    "FishCheckpointCodec",
    "FishHallState",
    "FishInstance",
    "FishInventory",
    "FishStateValidationContext",
    "FishStateValidationError",
    "OwnedBarbell",
    "PlayerState",
    "ProductionState",
    "RebirthState",
    "StatisticsState",
    "TorpedoState",
    "TrashManState",
    "TrashManUpgrade",
    "TrashProcessingState",
    "TrashStock",
    "WalletState",
    "normalize_player_state",
]
